"""Add iTunes artwork fields

Revision ID: 4e8500321596
Revises: 77032c1e3650
Create Date: 2026-01-22 20:52:49.195157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4e8500321596'
down_revision: Union[str, None] = '77032c1e3650'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('podcast', sa.Column('itunes_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('podcast', sa.Column('cover_url_sm', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True))
    op.add_column('podcast', sa.Column('cover_url_md', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True))
    op.add_column('podcast', sa.Column('cover_url_lg', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('podcast', 'cover_url_lg')
    op.drop_column('podcast', 'cover_url_md')
    op.drop_column('podcast', 'cover_url_sm')
    op.drop_column('podcast', 'itunes_id')
    # ### end Alembic commands ###
