"""create_podcast_table

Revision ID: 5996301373f9
Revises: 6a85b748a5ff
Create Date: 2026-01-20 18:21:06.275950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5996301373f9'
down_revision: Union[str, None] = '6a85b748a5ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('podcast',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('author', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cover_url', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('feed_url', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_podcast_feed_url'), 'podcast', ['feed_url'], unique=True)
    op.create_index(op.f('ix_podcast_is_featured'), 'podcast', ['is_featured'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_podcast_is_featured'), table_name='podcast')
    op.drop_index(op.f('ix_podcast_feed_url'), table_name='podcast')
    op.drop_table('podcast')
    # ### end Alembic commands ###
