"""Add Listen Notes fields and cache metadata

Revision ID: 77032c1e3650
Revises: 5996301373f9
Create Date: 2026-01-21 18:02:49.766408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '77032c1e3650'
down_revision: Union[str, None] = '5996301373f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cachemetadata',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cache_key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('last_fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cachemetadata_cache_key'), 'cachemetadata', ['cache_key'], unique=True)
    op.add_column('podcast', sa.Column('listenotes_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('podcast', sa.Column('publisher', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    op.add_column('podcast', sa.Column('total_episodes', sa.Integer(), nullable=True))
    op.add_column('podcast', sa.Column('listen_score', sa.Integer(), nullable=True))
    op.add_column('podcast', sa.Column('genre_ids', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    op.add_column('podcast', sa.Column('listenotes_url', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True))
    op.alter_column('podcast', 'feed_url',
               existing_type=sa.VARCHAR(length=2000),
               nullable=True)
    op.create_index(op.f('ix_podcast_listenotes_id'), 'podcast', ['listenotes_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_podcast_listenotes_id'), table_name='podcast')
    op.alter_column('podcast', 'feed_url',
               existing_type=sa.VARCHAR(length=2000),
               nullable=False)
    op.drop_column('podcast', 'listenotes_url')
    op.drop_column('podcast', 'genre_ids')
    op.drop_column('podcast', 'listen_score')
    op.drop_column('podcast', 'total_episodes')
    op.drop_column('podcast', 'publisher')
    op.drop_column('podcast', 'listenotes_id')
    op.drop_index(op.f('ix_cachemetadata_cache_key'), table_name='cachemetadata')
    op.drop_table('cachemetadata')
    # ### end Alembic commands ###
